name: Linked Jobs

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Message du premier job
        run: echo "premier job exécuté"

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Message du second job
        run: echo "second job exécuté après le premier"